import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildVaultSystemPrompt, hashVaultPrompt } from '@/ai/master/vault/prompt-builder';
import { FORBIDDEN_PATTERNS } from '@/ai/master/vault/__forbidden-patterns';

const BASE_INPUT = { vaultRoot: 'data/vault', campaignId: 'test', toolCount: 3 };

describe('buildVaultSystemPrompt — stability (REQ-022)', () => {
  it('1000 builds with identical input produce ONE unique SHA256', () => {
    const hashes = new Set<string>();
    for (let i = 0; i < 1000; i++) {
      hashes.add(hashVaultPrompt(buildVaultSystemPrompt(BASE_INPUT)));
    }
    expect(hashes.size).toBe(1);
  });

  it('1000 builds with language: "it" produce ONE unique SHA256', () => {
    const hashes = new Set<string>();
    for (let i = 0; i < 1000; i++) {
      hashes.add(hashVaultPrompt(buildVaultSystemPrompt({ ...BASE_INPUT, language: 'it' })));
    }
    expect(hashes.size).toBe(1);
  });
});

describe('buildVaultSystemPrompt — sensitivity', () => {
  it('different campaignId → different hash', () => {
    const a = hashVaultPrompt(buildVaultSystemPrompt({ ...BASE_INPUT, campaignId: 'a' }));
    const b = hashVaultPrompt(buildVaultSystemPrompt({ ...BASE_INPUT, campaignId: 'b' }));
    expect(a).not.toBe(b);
  });

  it('different toolCount (with matching vaultMutations) → different hash', () => {
    // Phase 02 — toolCount is now coupled to vaultMutations via the
    // consistency assertion. We sweep the (vaultMutations, toolCount)
    // pair together: read-only (false, 3) vs read-write (true, 4).
    const a = hashVaultPrompt(buildVaultSystemPrompt({ ...BASE_INPUT, toolCount: 3, vaultMutations: false }));
    const b = hashVaultPrompt(buildVaultSystemPrompt({ ...BASE_INPUT, toolCount: 4, vaultMutations: true }));
    expect(a).not.toBe(b);
  });

  it('different vaultRoot → different hash', () => {
    const a = hashVaultPrompt(buildVaultSystemPrompt({ ...BASE_INPUT, vaultRoot: 'data/vault' }));
    const b = hashVaultPrompt(buildVaultSystemPrompt({ ...BASE_INPUT, vaultRoot: '/abs/vault' }));
    expect(a).not.toBe(b);
  });

  it('language presence changes hash', () => {
    const withLang = hashVaultPrompt(buildVaultSystemPrompt({ ...BASE_INPUT, language: 'it' }));
    const without = hashVaultPrompt(buildVaultSystemPrompt(BASE_INPUT));
    expect(withLang).not.toBe(without);
  });

  it('empty language string is treated as no language (preserves hash)', () => {
    const empty = hashVaultPrompt(buildVaultSystemPrompt({ ...BASE_INPUT, language: '' }));
    const without = hashVaultPrompt(buildVaultSystemPrompt(BASE_INPUT));
    expect(empty).toBe(without);
  });
});

describe('buildVaultSystemPrompt — content sanity', () => {
  it('includes the literal toolCount in the protocol line', () => {
    const prompt = buildVaultSystemPrompt({ ...BASE_INPUT, toolCount: 3 });
    expect(prompt).toContain('3 listed tools');
  });

  it('references /tools/index.md as discovery entry point (REQ-012)', () => {
    const prompt = buildVaultSystemPrompt(BASE_INPUT);
    expect(prompt).toContain('/tools/index.md');
  });

  it('language clause appears only when language is set', () => {
    const without = buildVaultSystemPrompt(BASE_INPUT);
    const withLang = buildVaultSystemPrompt({ ...BASE_INPUT, language: 'it' });
    expect(without).not.toContain('Respond in language');
    expect(withLang).toContain('Respond in language: it.');
  });

  it('matches the locked snapshot for a fixed input', () => {
    const prompt = buildVaultSystemPrompt({ vaultRoot: 'data/vault', campaignId: 'test-camp', toolCount: 3 });
    // Snapshot baseline locked in this PR. Any drift here surfaces in
    // code review as a deliberate change to the prefix-cache identity.
    expect(prompt).toBe([
      'You are an experienced D&D 5e Dungeon Master.',
      '',
      // Phase 04 (REQ-035) — locked `## Your role` block, byte-identical to the
      // builder output (regenerated by copying, NOT hand-retyped, to avoid
      // em-dash/ellipsis drift). Static + unconditional, so it appears here too.
      '## Your role',
      '',
      'Narrate in second person ("you …"). You control the world — environment,',
      'NPCs, and the CONSEQUENCES of what the player declares. You do NOT control',
      'the player\'s character.',
      '',
      '- The player decides their character\'s actions, words, and intentions.',
      '  Narrate the OUTCOME of an action the player stated — never invent actions,',
      '  dialogue, decisions, or successes the player did not declare.',
      '- Brief connective body language is allowed ("ti volti di scatto",',
      '  "stringi la presa") but NEVER a decision, a line of dialogue, or an',
      '  outcome the player didn\'t declare.',
      '- Multiplayer: never speak or decide for ANY player character. When another',
      '  character should act next, close your beat by addressing them BY NAME —',
      '  the system hands them the turn.',
      '- End with an open cue ("Che fai?"). Never a numbered menu of options.',
      '',
      'Example — player writes "provo ad attaccarlo":',
      '  GOOD: "Ti lanci in avanti; la tua lama trova un varco nella guardia',
      '        del nemico, che barcolla con un grugnito."',
      '  BAD:  "Luffy si lancia e decide di colpire al fianco. \'GUM GUM!\' grida,',
      '        mettendo a segno il colpo." (invents the PC\'s action, words, outcome)',
      '',
      '## Knowledge layout',
      '',
      "Your knowledge lives in a markdown vault at root 'data/vault'.",
      '- Static knowledge: /handbook/<category>/<id>.md',
      '- Active campaign: /campaigns/test-camp/ (reserved — populated in a later release)',
      '',
      '## Tool usage protocol',
      '',
      "If you don't know what tools exist, your FIRST action is to read /tools/index.md.",
      'After that, use any of the 3 listed tools directly.',
      '',
      'Keep responses concise.',
    ].join('\n'));
  });
});

describe('buildVaultSystemPrompt — REQ-022 lint enforcement', () => {
  it('builder source contains no forbidden patterns', () => {
    const src = readFileSync(resolve(process.cwd(), 'src/ai/master/vault/prompt-builder.ts'), 'utf8');
    const violations = FORBIDDEN_PATTERNS.filter(({ re }) => re.test(src)).map(({ name }) => name);
    expect(violations).toEqual([]);
  });
});

describe('hashVaultPrompt', () => {
  it('produces a 64-char hex SHA256', () => {
    const hash = hashVaultPrompt('test');
    expect(hash).toMatch(/^[a-f0-9]{64}$/);
  });
});

// Phase 04 — anti-railroading `## Your role` block (REQ-035).
// The block is UNCONDITIONAL (present whether vaultMutations is true or false)
// and STATIC (no per-input variation → preserves REQ-022 byte-stability). The
// content is LOCKED in 04-CONTEXT.md §"Exact block content". These assertions
// pin the load-bearing tokens; the byte-exact reproduction is enforced by the
// regenerated locked-snapshot test in `content sanity`.
describe('buildVaultSystemPrompt — Phase 04 anti-railroading (REQ-035)', () => {
  const READ_WRITE = { vaultRoot: 'data/vault', campaignId: 'test', toolCount: 4, vaultMutations: true };

  it('read-only prompt contains the "## Your role" block', () => {
    const prompt = buildVaultSystemPrompt(BASE_INPUT);
    expect(prompt).toContain('## Your role');
  });

  it('read-write prompt (vaultMutations:true) ALSO contains "## Your role" (unconditional)', () => {
    const prompt = buildVaultSystemPrompt(READ_WRITE);
    expect(prompt).toContain('## Your role');
  });

  it('instructs second-person narration', () => {
    const prompt = buildVaultSystemPrompt(BASE_INPUT);
    expect(prompt).toContain('second person');
  });

  it('forbids inventing the PC\'s actions', () => {
    const prompt = buildVaultSystemPrompt(BASE_INPUT);
    expect(prompt).toContain('never invent actions');
  });

  it('includes the GOOD/BAD worked example markers', () => {
    const prompt = buildVaultSystemPrompt(BASE_INPUT);
    expect(prompt).toContain('GOOD:');
    expect(prompt).toContain('BAD:');
  });

  it('tells the master to address the next character BY NAME (multiplayer hand-off)', () => {
    const prompt = buildVaultSystemPrompt(BASE_INPUT);
    expect(prompt).toContain('BY NAME');
  });

  it('vault prompt stays under 2048 bytes for BASE_INPUT', () => {
    const prompt = buildVaultSystemPrompt(BASE_INPUT);
    expect(Buffer.byteLength(prompt, 'utf8')).toBeLessThan(2048);
  });
});

describe('buildVaultSystemPrompt — Phase 02 vaultMutations gate', () => {
  // The Phase 02 contract: vaultMutations:true ⇒ toolCount:4 (apply_event
  // advertised); vaultMutations !== true ⇒ toolCount:3 (read-only). Pairs
  // are validated by the consistency assertion at the top of the builder.
  const READ_ONLY = { vaultRoot: 'data/vault', campaignId: 'test', toolCount: 3 };
  const READ_WRITE = { vaultRoot: 'data/vault', campaignId: 'test', toolCount: 4, vaultMutations: true };

  it('vaultMutations:true with toolCount:4 produces a prompt that mentions apply_event', () => {
    const prompt = buildVaultSystemPrompt(READ_WRITE);
    expect(prompt).toContain('apply_event');
  });

  it('vaultMutations:true mentions character UUID (NIT 1 — not character name)', () => {
    const prompt = buildVaultSystemPrompt(READ_WRITE);
    expect(prompt).toContain('character UUID');
  });

  it('vaultMutations:false (omitted) produces a prompt that does NOT mention apply_event', () => {
    const prompt = buildVaultSystemPrompt(READ_ONLY);
    expect(prompt).not.toContain('apply_event');
  });

  it('vaultMutations:false (explicit) produces a prompt that does NOT mention apply_event', () => {
    const prompt = buildVaultSystemPrompt({ ...READ_ONLY, vaultMutations: false });
    expect(prompt).not.toContain('apply_event');
  });

  it('consistency assertion — vaultMutations:true with toolCount:3 throws', () => {
    expect(() =>
      buildVaultSystemPrompt({ ...READ_ONLY, vaultMutations: true }),
    ).toThrow(/vaultMutations:true requires toolCount:4/);
  });

  it('consistency assertion — vaultMutations:false with toolCount:4 throws', () => {
    expect(() =>
      buildVaultSystemPrompt({ vaultRoot: 'data/vault', campaignId: 'test', toolCount: 4, vaultMutations: false }),
    ).toThrow(/requires toolCount:3/);
  });

  it('consistency assertion — toolCount:4 without vaultMutations (undefined) throws', () => {
    expect(() =>
      buildVaultSystemPrompt({ vaultRoot: 'data/vault', campaignId: 'test', toolCount: 4 }),
    ).toThrow(/requires toolCount:3/);
  });

  it('natural hash divergence — read-only prompt vs read-write prompt produce different hashes (Change 4 claim)', () => {
    const promptReadOnly = buildVaultSystemPrompt(READ_ONLY);
    const promptReadWrite = buildVaultSystemPrompt(READ_WRITE);
    expect(hashVaultPrompt(promptReadOnly)).not.toBe(hashVaultPrompt(promptReadWrite));
  });

  it('vaultMutations:true 1000 builds produce ONE unique SHA256 (stability preserved)', () => {
    const hashes = new Set<string>();
    for (let i = 0; i < 1000; i++) {
      hashes.add(hashVaultPrompt(buildVaultSystemPrompt(READ_WRITE)));
    }
    expect(hashes.size).toBe(1);
  });
});

// Phase 02.1 — character roster injection (smoke 2026-05-26 follow-up).
// Smoke testing revealed qwen3:30b cannot deduce character UUIDs from the
// dispatcher error marker; it just invents ids. Injecting the roster
// directly into the system prompt closes the gap.
describe('buildVaultSystemPrompt — Phase 02.1 character roster injection', () => {
  const baseRW = {
    vaultRoot: 'data/vault',
    campaignId: 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
    toolCount: 4,
    vaultMutations: true as const,
  };
  const ROSTER = [
    { id: '25158592-15cf-41c8-99b2-44dde5f73702', name: 'Luffy' },
    { id: '84185b08-8032-4cb7-a30c-9212a16dfb05', name: 'Usopp' },
  ];

  it('includes the "Available characters" header when vaultMutations:true and characters[] is non-empty', () => {
    const out = buildVaultSystemPrompt({ ...baseRW, characters: ROSTER });
    expect(out).toContain('## Available characters');
  });

  it('lists every character with its UUID in backticks', () => {
    const out = buildVaultSystemPrompt({ ...baseRW, characters: ROSTER });
    expect(out).toContain('Luffy: `25158592-15cf-41c8-99b2-44dde5f73702`');
    expect(out).toContain('Usopp: `84185b08-8032-4cb7-a30c-9212a16dfb05`');
  });

  it('warns the model NOT to invent identifiers like pc-001', () => {
    const out = buildVaultSystemPrompt({ ...baseRW, characters: ROSTER });
    expect(out).toMatch(/do NOT invent.*pc-001/i);
  });

  it('skips the roster section when characters is undefined', () => {
    const out = buildVaultSystemPrompt({ ...baseRW });
    expect(out).not.toContain('## Available characters');
  });

  it('skips the roster section when characters is empty array', () => {
    const out = buildVaultSystemPrompt({ ...baseRW, characters: [] });
    expect(out).not.toContain('## Available characters');
  });

  it('does NOT inject roster when vaultMutations is false (Phase 01 read-only prompts stay clean)', () => {
    const out = buildVaultSystemPrompt({
      ...baseRW,
      toolCount: 3,
      vaultMutations: false,
      characters: ROSTER,
    });
    expect(out).not.toContain('## Available characters');
  });

  it('roster order is preserved (caller controls order)', () => {
    const out1 = buildVaultSystemPrompt({ ...baseRW, characters: ROSTER });
    const reversed = [ROSTER[1]!, ROSTER[0]!];
    const out2 = buildVaultSystemPrompt({ ...baseRW, characters: reversed });
    // Match the full roster-line form (`Name: \`uuid\``) rather than the bare
    // name: Phase 04's worked example mentions "Luffy" in prose, so a bare
    // indexOf('Luffy') would find the example, not the roster entry. The
    // `Name: \`uuid\`` form is unique to the roster block.
    const luffyLine = (id: string) => 'Luffy: `' + id + '`';
    const usoppLine = (id: string) => 'Usopp: `' + id + '`';
    const idxLuffyOut1 = out1.indexOf(luffyLine(ROSTER[0]!.id));
    const idxUsoppOut1 = out1.indexOf(usoppLine(ROSTER[1]!.id));
    const idxLuffyOut2 = out2.indexOf(luffyLine(ROSTER[0]!.id));
    const idxUsoppOut2 = out2.indexOf(usoppLine(ROSTER[1]!.id));
    expect(idxLuffyOut1).toBeLessThan(idxUsoppOut1);
    expect(idxUsoppOut2).toBeLessThan(idxLuffyOut2);
  });

  it('roster injection produces a different hash than no-roster (deterministic divergence)', () => {
    const noRoster = buildVaultSystemPrompt({ ...baseRW });
    const withRoster = buildVaultSystemPrompt({ ...baseRW, characters: ROSTER });
    expect(hashVaultPrompt(noRoster)).not.toBe(hashVaultPrompt(withRoster));
  });

  it('1000 builds with the same roster produce ONE unique hash (stability preserved)', () => {
    const hashes = new Set<string>();
    for (let i = 0; i < 1000; i++) {
      hashes.add(hashVaultPrompt(buildVaultSystemPrompt({ ...baseRW, characters: ROSTER })));
    }
    expect(hashes.size).toBe(1);
  });
});
